#spring:
#  profiles:
#    active: prod # 기본 프로파일 설정



spring:
  config:
    activate:
      on-profile: dev # 개발 모드 (H2 사용)
  datasource:
    url: jdbc:mysql://localhost:3306/db_clubreview
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: Pqw/FGD2GMTRcxU4WDANQVqHyalfmCIISxigQYOBEYE8+sD52um+dxSF64TwGhjcTyMGzu9/cLshZ5+WnmcUEA==
  expiration: 86400

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
seed:
  run-on-startup: true
  truncate-before: true
  dependent-tables: [review]
  default-average-rating: 0.0
  create-reviews: true
  csv-path: classpath:seed/seoul_clubs_pubs.csv
  use-csv-description: false   # 제 자동 설명 사용

kakao:
  host: https://dapi.kakao.com
  restApiKey: "8ec4a0631236aef6effc281e57c9e41a"
  timeoutMs: 5000
  defaultRadius: 3000

#
#spring:
#  config:
#    activate:
#      on-profile: prod # 운영 모드
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_clubreview
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  thymeleaf:
#    prefix: classpath:/templates/ # 템플릿 기본 경로
#    suffix: .html                 # 템플릿 파일 확장자
#    cache: false                  # 개발 시 캐시 비활성화
#  spring:
#    web:
#      resources:
#        static-locations: classpath:/static/
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE



---

#spring:
#  config:
#    activate:
#      on-profile: local # 로컬 MySQL 모드
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_clubreview
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#-Dspring.profiles.active=local
#-Dspring.profiles.active=prod